apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: test
  labels:
    app: postgres
stringData:
  POSTGRES_DB: feast
  POSTGRES_USER: feast
  POSTGRES_PASSWORD: feast  # pragma: allowlist secret
---
apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
  namespace: test
stringData:
  sql: |
    path: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.test.svc.cluster.local:5432/${POSTGRES_DB}
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
  postgres: |
    host: postgres.test.svc.cluster.local
    port: 5432
    database: ${POSTGRES_DB}
    db_schema: public
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
# Static scaling: 3 replicas with DB-backed persistence
apiVersion: feast.dev/v1
kind: FeatureStore
metadata:
  name: sample-scaling-static
  namespace: test
spec:
  feastProject: my_project
  replicas: 3
  services:
    onlineStore:
      persistence:
        store:
          type: postgres
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
        - secretRef:
            name: postgres-secret
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
